# version: "3.7"

# services:
#   app: 
#     image: node:12-alpine
#     command: sh -c "npm i && npm run dev"
#     ports:
#       - 3000:3333
#     working_dir: /app
#     volumes:
#        - ./:/app
#     environment:
#       MONGO_URI: mongo

#   mongo:
#     image: mongo
#     volumes:
#       - mongo-data: /data/db

# volumes:
#   mongo-data:

# ABOVE ONE IS NOT WORKING CAUSE OF DOCKER_COMPOSE VERSION ISSUE
# this compose is for DEV ENV

version: '3'

services:
  app:
    container_name: chat_app
    image: node:12-alpine
    environment:
      - MONGO_URI=mongodb://db:27017/chatApp
    ports:
      - 3333:3333
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    command: sh -c 'npm i && npm run dev'

  db:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
